global:
  storageClass: "nfs-client"
  postgresql:
    password: "support"

postgresql:
  replicaCount: 3
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 6
    successThreshold: 1
    exec:
      command:
        - sh
        - -c
        - exec pg_isready -U postgres
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - postgresql
          topologyKey: "kubernetes.io/hostname"
  nodeSelector:
    node-role.kubernetes.io/msr: "true"

pgpool:
  replicaCount: 1
  nodeSelector:
    node-role.kubernetes.io/msr: "true"

